# Generated by Django 3.1.7 on 2021-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(max_length=10)),
                ('working_hours', models.JSONField(default=[])),
                ('regions', models.ManyToManyField(related_name='couriers', to='api.Region')),
            ],
        ),
    ]
