# Generated by Django 3.1.7 on 2021-03-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'assigned'), (2, 'completed'), (3, 'canceled')], default=0),
        ),
        migrations.CreateModel(
            name='Delivering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
