# Generated by Django 3.1.7 on 2021-03-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_courier_lift_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivering',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='delivering',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
